### ISSUE TITLE
Cannot connect to scp or ftp

### ISSUE THREAD

**Issue by ashleyhood** [Andr3as/Codiad-CodeTransfer#1]
When trying to connect to a ssh server or ftp server I get no response from UI.

I ran web developer tools on both Chrome and Firefox and both showed a 500 error calling the controller.

Here is the error that is displayed in Chrome:

> **Request URL:**https://codiad.wightsites.com/plugins/Codiad-CodeTransfer-master/controller.php?action=setMode&mode=scp
> **Request Method:**GET
> **Status Code:**500 Internal Server Error
> 
> **Request Headers**
> **Accept:**application/json, text/javascript, _/_; q=0.01
> **Accept-Encoding:**gzip,deflate,sdch
> **Accept-Language:**en-GB,en-US;q=0.8,en;q=0.6
> **Connection:**keep-alive
> **Cookie:**1a5ac4d721f222xafea03f282a3ef168=iv04a0kdk1lp04mmjkp2g6m9a2
> **DNT:**1
> **Host:**codiad.wightsites.com
> **Referer:**https://codiad.wightsites.com/
> **User-Agent:**Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36
> **X-Requested-With:**XMLHttpRequest
> 
> **Query String Parameters**
> **action:**setMode
> **mode:**scp
> 
> **Response Headers**
> **Connection:**close
> **Content-Encoding:**gzip
> **Content-Length:**20
> **Content-Type:**text/html
> **Date:**Thu, 15 Aug 2013 11:07:32 GMT
> **Server:**Apache/2.2.22 (Ubuntu)
> **Vary:**Accept-Encoding
> **X-Powered-By:**PHP/5.3.10-1ubuntu3.7

**Comment by lcherone** [comment]
PHP >= 5.4 supports for array dereferencing. OP was using PHP/5.3.10 http://php.net/manual/en/migration54.new-features.php
