### ISSUE TITLE
upload an entire directory from local disk to Codiad Server via FTP

### ISSUE THREAD

**Issue by rafasashi** [Andr3as/Codiad-CodeTransfer#10]
Peer to the following issue: https://github.com/Codiad/Codiad/issues/842

I am thinking of using the Codetransfer Plugin to upload an entire directory from local disk to Codiad Server.

Is it possible to make the local (left) part pointing to C: instead of the current project?

**Comment by Andr3as** [comment]
No, it's not possible to access the local file system from your browser. Imagine a browser script could read your files in background, this would be a great security problem.

Another way for you would be to install a ftp or ssh server on your local computer and use CodeTransfer to access it (in the right part).
