### ISSUE TITLE
Edit on Remote

### ISSUE THREAD

**Issue by s3w47m88** [Andr3as/Codiad-CodeTransfer#11]
I apologize if this isn't the correct location for this but I'm wondering if there is the ability to edit on the remote server?

**Comment by Andr3as** [comment]
With some work I think it would be possible to integrate. Maybe if find some time this summer.

**Comment by MarioCroSite** [comment]
Any news about update edit on remote ?

**Comment by Andr3as** [comment]
I had finally some time to create a draft  (#12). I will test it further before merging it.

**Comment by Andr3as** [comment]
Integrated with Version 1.3.0
