### ISSUE TITLE
YARA.WebShell_Generic_PHP_5.UNOFFICIAL

### ISSUE THREAD

**Issue by jchevali** [Andr3as/Codiad-CodeTransfer#13]
The virus scanner provided with CPanel shows me a warning for "controller.php".
I'm unable to determine whether it's a false positive, or how to avoid it.
![1185511](https://cloud.githubusercontent.com/assets/8971316/25255307/c66c8454-2621-11e7-9f38-1a335f610ee3.jpg)

**Comment by Andr3as** [comment]
It should be a false positive. You can take a look on the [source code](https://github.com/Andr3as/Codiad-CodeGit/blob/master/controller.php).

**Comment by digitart** [comment]
Your false possitive come from a combination between coding and function/var names in controller.php file. To fix it change varname entirely in getFullPermissions() function from $perms to whatever you like i.e. $avperms and you will be able to uploadit.

**Comment by Andr3as** [comment]
👍 Thanks a lot.
