### ISSUE TITLE
Can't display FTP directory contents

### ISSUE THREAD

**Issue by trst** [Andr3as/Codiad-CodeTransfer#2]
I'm having trouble getting your plugin properly setup. I'm sure it's just user error on my part, but when I connect to an FTP server I can't display the directory contents.

This is what I see:

![image](https://f.cloud.github.com/assets/1895782/1051482/c52402a8-10cb-11e3-94d9-b8929c73a87e.png)

Any thoughts?

**Comment by Andr3as** [comment]
Please reopen if required
