### ISSUE TITLE
Open project by FTP

### ISSUE THREAD

**Issue by blueparry** [Andr3as/Codiad-CodeTransfer#4]
Hey guys,

i have other suggestion to better codiad.

Actually we can create project by workspace, folder on same server or github repository.

So, i would like to suggest add connection by FTP. So if we can add project by FTP was awesome.

Tnks!

**Comment by cheiff** [comment]
Hi, 

just looking for some advice /idea for mounting the ftp directories in the codiad server with curlftpfs.
I can add a function when codiad loads that checks for the remote projects and mounts them so the user can access those projects. I think I know more or less how to do that.
But, how could I detect that the user is not using them anymore and then unmount them?
I am thinking of adding some sort of cron task that checks for "unmountable" directories and unmounts them, but how could I mark them as unmountables? Let's assume that the user is not signin out, just letting the session stale.
Does it make sense to use the poller to do some sort of updating e.g. a file per user and then externally check that if that file hasn't been updated in a while, it would be safe to unmount the remote folders? 
Does any of this make sense? How do other remote editors handle this?
What would be the problem of leaving those connections stale? 

Any comment will be welcomed, thanks!

**Comment by neocamel** [comment]
I know this is an old thread, but I'm looking for something similar and was wondering if anyone ever figured this out?

Ideally, it would be great if remote FTP folders could be listed in the 'projects' window, so I can make edits to remote servers from my codiad install. I suppose I could install a separate copy of codiad on that remote server, and just access it from their IP, but it would really be ideal if I could have all my FTP connections consolidated in one codiad install.  

Sort of how CodeAnywhere allows you to set up remote projects?
