### ISSUE TITLE
Feature request: Add a way to save the FTP credentials/details 

### ISSUE THREAD

**Issue by jamieisboss** [Andr3as/Codiad-CodeTransfer#6]
Per project, so that I don't have to retype all my login details every time I want to transfer a file

**Comment by Andr3as** [comment]
This feature already exists, just close the dialog by clicking on "hide" and you can continue your work as long as you are logged in at Codiad.

**Comment by Andr3as** [comment]
Reopen if this answer does not fit your feature request.
