### ISSUE TITLE
Feature request: add an option to mirror the navigation on both sides

### ISSUE THREAD

**Issue by jamieisboss** [Andr3as/Codiad-CodeTransfer#7]
Because for many of my projects the folder structure is identical both sides of the ftp connection, if you could make it so that, for example when I descend into folder_1 locally it does the same on the remote side that would be a great time saver.

Many thanks 

Jamie

**Comment by Andr3as** [comment]
:+1:

**Comment by Andr3as** [comment]
Added with [056097db](056097db94efe3384ead67e69fc61b79add75f6b)
