### ISSUE TITLE
Mount the FTP remote as a project?

### ISSUE THREAD

**Issue by cheiff** [Andr3as/Codiad-CodeTransfer#8]
Hi,
in other words, work directly on files on a different server.
Would that be possible?
Thanks, regards.

**Comment by Andr3as** [comment]
This question was asked several times (f.e. #4). Since this feature requires big changes on the Codiad core, I do not believe it would be possible in the next time.

**Comment by cheiff** [comment]
OK. Thank you for answering anyway. Kind regards.
